### ISSUE TITLE
Frontend Master Task - Registry

### ISSUE THREAD

**Issue by hammeiam** [saddle-finance/saddle-frontend#933]
- [ ] Add Registry ABIs
- [ ] Add registry contract hooks
- [ ] Add Chain and Block to redux state
- [ ] #932 
- [ ] Remove reference to icon from tokens, store as either address (chain-specific) or symbol
- [ ] Move POOLS_MAP into redux state
- [ ] Move TOKENS_MAP into a redux state getter
- [ ] Remove references to chainId when reading tokens or pools, except at the top-level state
- [ ] Write getPools & getTokens functions using registry
- [ ] Write new getTokenPrices function using chainId and new getTokens
- [ ] Write version of getThirdPartyDataForPool that uses address instead of name

**Comment by ug02fast** [comment]
What do you think about moving these to a provider instead to avoid having to use Redux? Is there a particular reason for using Redux?

> Move POOLS_MAP into redux state
> Move TOKENS_MAP into a redux state getter
